
import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Checkbox } from '@/components/ui/checkbox';
import { AlertTriangle, CheckCircle, Clock, FileText, Shield } from 'lucide-react';
import { BillingSafeguard as BillingSafeguardType, ClinicalNote } from '@/types/billingBreakdown';
import { validateBillingReadiness, generateClinicalNotes } from '@/utils/billingValidation';
import { useToast } from '@/hooks/use-toast';

interface BillingSafeguardProps {
  taskId: string;
  patientId: string;
  cptCode: string;
  timeSpent: number;
  stabilityMetrics: Record<string, string>;
  onBillingSubmit: (safeguard: BillingSafeguardType) => void;
  onAutoFill: () => void;
}

export const BillingSafeguard: React.FC<BillingSafeguardProps> = ({
  taskId,
  patientId,
  cptCode,
  timeSpent,
  stabilityMetrics,
  onBillingSubmit,
  onAutoFill
}) => {
  const { toast } = useToast();
  const [clinicalNotes, setClinicalNotes] = useState<ClinicalNote>({
    stabilityAssessment: '',
    functionalStatus: '',
    riskFactors: '',
    interventions: '',
    followUpPlan: '',
    medicationReview: '',
    careCoordination: ''
  });

  const [validation, setValidation] = useState(validateBillingReadiness(clinicalNotes, timeSpent));
  const [isAutoFilled, setIsAutoFilled] = useState(false);
  const [confirmSubmission, setConfirmSubmission] = useState(false);

  useEffect(() => {
    const newValidation = validateBillingReadiness(clinicalNotes, timeSpent);
    setValidation(newValidation);
  }, [clinicalNotes, timeSpent]);

  const handleAutoFill = () => {
    const autoGeneratedNotes = generateClinicalNotes(stabilityMetrics);
    setClinicalNotes(prev => ({
      ...prev,
      ...autoGeneratedNotes
    }));
    setIsAutoFilled(true);
    onAutoFill();
    
    toast({
      title: "Clinical Notes Auto-Generated",
      description: "Review and modify the generated notes as needed before submitting for billing.",
    });
  };

  const handleNoteChange = (field: keyof ClinicalNote, value: string) => {
    setClinicalNotes(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleSubmitForBilling = () => {
    if (!validation.isValid) {
      toast({
        title: "Cannot Submit for Billing",
        description: "Please complete all required fields before submitting.",
        variant: "destructive"
      });
      return;
    }

    const safeguard: BillingSafeguardType = {
      taskId,
      patientId,
      cptCode,
      timeSpent,
      clinicalNotes,
      validation,
      isReadyForBilling: true,
      submittedAt: new Date(),
      submittedBy: 'Current User'
    };

    onBillingSubmit(safeguard);
    
    toast({
      title: "Submitted for Billing",
      description: `Task ${taskId} has been successfully submitted for billing review.`,
    });
  };

  const getFieldStatus = (field: keyof ClinicalNote) => {
    const requirement = validation.requiredFields.find(req => req.field === field);
    return requirement?.completed || false;
  };

  return (
    <Card className="border-blue-200">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Shield className="text-blue-600" size={20} />
          Billing Safeguard System
          <Badge className={validation.isValid ? "bg-green-100 text-green-800" : "bg-yellow-100 text-yellow-800"}>
            {validation.completionPercentage}% Complete
          </Badge>
        </CardTitle>
        <div className="flex items-center gap-4 text-sm text-gray-600">
          <div className="flex items-center gap-1">
            <Clock size={16} />
            <span>{timeSpent} minutes logged</span>
          </div>
          <div className="flex items-center gap-1">
            <FileText size={16} />
            <span>CPT Code: {cptCode}</span>
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Progress Overview */}
        <div className="space-y-2">
          <div className="flex justify-between text-sm">
            <span>Documentation Progress</span>
            <span>{validation.completionPercentage}%</span>
          </div>
          <Progress value={validation.completionPercentage} className="h-2" />
        </div>

        {/* Auto-fill Option */}
        <Card className="bg-blue-50 border-blue-200">
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <h4 className="font-medium text-blue-900">Auto-Generate Clinical Notes</h4>
                <p className="text-sm text-blue-700">Generate initial documentation based on stability metrics</p>
              </div>
              <Button 
                onClick={handleAutoFill}
                variant="outline"
                className="border-blue-300 text-blue-700 hover:bg-blue-100"
                disabled={isAutoFilled}
              >
                {isAutoFilled ? 'Notes Generated' : 'Auto-Fill Notes'}
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Clinical Notes Fields */}
        <div className="space-y-4">
          <h4 className="font-medium">Clinical Documentation</h4>
          
          {Object.entries(clinicalNotes).map(([field, value]) => {
            const fieldKey = field as keyof ClinicalNote;
            const isComplete = getFieldStatus(fieldKey);
            const requirement = validation.requiredFields.find(req => req.field === field);
            
            return (
              <div key={field} className="space-y-2">
                <div className="flex items-center gap-2">
                  <label className="text-sm font-medium capitalize">
                    {field.replace(/([A-Z])/g, ' $1').trim()}
                  </label>
                  {isComplete ? (
                    <CheckCircle className="text-green-600" size={16} />
                  ) : (
                    <AlertTriangle className="text-yellow-600" size={16} />
                  )}
                </div>
                <Textarea
                  value={value}
                  onChange={(e) => handleNoteChange(fieldKey, e.target.value)}
                  placeholder={requirement?.description || `Enter ${field}...`}
                  className={isComplete ? "border-green-300" : "border-yellow-300"}
                  rows={3}
                />
                <div className="text-xs text-gray-500">
                  {value.length} characters • {requirement?.description}
                </div>
              </div>
            );
          })}
        </div>

        {/* Validation Summary */}
        {(validation.errors.length > 0 || validation.warnings.length > 0) && (
          <Card className="border-yellow-200 bg-yellow-50">
            <CardContent className="p-4">
              <h4 className="font-medium text-yellow-800 mb-2">Validation Summary</h4>
              {validation.errors.length > 0 && (
                <div className="mb-2">
                  <p className="text-sm font-medium text-red-700">Errors:</p>
                  <ul className="text-sm text-red-600 list-disc list-inside">
                    {validation.errors.map((error, index) => (
                      <li key={index}>{error}</li>
                    ))}
                  </ul>
                </div>
              )}
              {validation.warnings.length > 0 && (
                <div>
                  <p className="text-sm font-medium text-yellow-700">Warnings:</p>
                  <ul className="text-sm text-yellow-600 list-disc list-inside">
                    {validation.warnings.map((warning, index) => (
                      <li key={index}>{warning}</li>
                    ))}
                  </ul>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {/* Submission Controls */}
        <div className="border-t pt-4">
          <div className="flex items-center space-x-2 mb-4">
            <Checkbox 
              id="confirm-submission"
              checked={confirmSubmission}
              onCheckedChange={(checked) => setConfirmSubmission(checked as boolean)}
            />
            <label 
              htmlFor="confirm-submission" 
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              I confirm that all clinical documentation is accurate and complete
            </label>
          </div>
          
          <div className="flex gap-2">
            <Button
              onClick={handleSubmitForBilling}
              disabled={!validation.isValid || !confirmSubmission}
              className="bg-green-600 hover:bg-green-700"
            >
              Submit for Billing
            </Button>
            <Button variant="outline">
              Save Draft
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
};
