
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { AlertTriangle, TrendingUp, Calendar, Lightbulb, Brain, ChevronRight, Clock, FileText, Activity } from 'lucide-react';
import { TaskCallContext } from '@/types/taskCallIntegration';

interface TaskSpecificInsight {
  id: string;
  type: 'task_context' | 'patient_history' | 'risk_factor' | 'medication_alert' | 'behavioral_pattern';
  title: string;
  description: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  confidence: number;
  taskRelevance: number;
  suggestedQuestions: string[];
  evidenceSource: string;
  lastUpdated: string;
}

interface TaskPreCallIntelligenceProps {
  taskContext: TaskCallContext;
  onStartCall: () => void;
}

export const TaskPreCallIntelligence: React.FC<TaskPreCallIntelligenceProps> = ({
  taskContext,
  onStartCall
}) => {
  // Mock task-specific insights - would be generated by AI based on task context
  const taskInsights: TaskSpecificInsight[] = [
    {
      id: 'insight-1',
      type: 'task_context',
      title: 'Monthly Stability Assessment Due',
      description: 'Patient requires comprehensive stability review including medication effectiveness, side effects, and mood tracking progress',
      priority: 'high',
      confidence: 0.95,
      taskRelevance: 1.0,
      suggestedQuestions: [
        'How have you been feeling since our last check-in?',
        'Any changes in your mood or energy levels?',
        'How consistent have you been with your medication?',
        'Any side effects you\'ve noticed?'
      ],
      evidenceSource: 'Care plan protocol',
      lastUpdated: '2 hours ago'
    },
    {
      id: 'insight-2',
      type: 'medication_alert',
      title: 'Recent Medication Increase',
      description: 'Sertraline dosage increased from 50mg to 100mg two weeks ago. Monitor for effectiveness and side effects.',
      priority: 'critical',
      confidence: 0.98,
      taskRelevance: 0.9,
      suggestedQuestions: [
        'How are you tolerating the increased medication dose?',
        'Any new side effects since the increase?',
        'Have you noticed any improvement in symptoms?'
      ],
      evidenceSource: 'Medication history',
      lastUpdated: '1 day ago'
    },
    {
      id: 'insight-3',
      type: 'behavioral_pattern',
      title: 'Improved Sleep Pattern Trend',
      description: 'Sleep quality scores have improved 40% over the past two weeks, suggesting positive treatment response',
      priority: 'medium',
      confidence: 0.87,
      taskRelevance: 0.8,
      suggestedQuestions: [
        'How has your sleep been lately?',
        'What changes have helped improve your sleep?',
        'Are you following your sleep hygiene recommendations?'
      ],
      evidenceSource: 'Wearable device data',
      lastUpdated: '6 hours ago'
    },
    {
      id: 'insight-4',
      type: 'risk_factor',
      title: 'Missed Therapy Session',
      description: 'Patient missed last scheduled therapy session. Important to assess engagement and barriers.',
      priority: 'high',
      confidence: 0.92,
      taskRelevance: 0.7,
      suggestedQuestions: [
        'I noticed you missed your last therapy session. Is everything okay?',
        'Any barriers preventing you from attending therapy?',
        'How do you feel about continuing with therapy?'
      ],
      evidenceSource: 'Appointment system',
      lastUpdated: '3 days ago'
    }
  ];

  const getInsightIcon = (type: string) => {
    switch (type) {
      case 'task_context': return <FileText className="w-4 h-4" />;
      case 'patient_history': return <Activity className="w-4 h-4" />;
      case 'risk_factor': return <AlertTriangle className="w-4 h-4" />;
      case 'medication_alert': return <Calendar className="w-4 h-4" />;
      case 'behavioral_pattern': return <TrendingUp className="w-4 h-4" />;
      default: return <Lightbulb className="w-4 h-4" />;
    }
  };

  const getInsightColor = (type: string) => {
    switch (type) {
      case 'task_context': return 'bg-blue-100 text-blue-800 border-blue-200';
      case 'patient_history': return 'bg-purple-100 text-purple-800 border-purple-200';
      case 'risk_factor': return 'bg-red-100 text-red-800 border-red-200';
      case 'medication_alert': return 'bg-orange-100 text-orange-800 border-orange-200';
      case 'behavioral_pattern': return 'bg-green-100 text-green-800 border-green-200';
      default: return 'bg-gray-100 text-gray-800 border-gray-200';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'critical': return 'bg-red-500 text-white';
      case 'high': return 'bg-orange-500 text-white';
      case 'medium': return 'bg-yellow-500 text-white';
      case 'low': return 'bg-green-500 text-white';
      default: return 'bg-gray-500 text-white';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="border-l-4 border-l-purple-500">
        <CardHeader className="bg-purple-50">
          <CardTitle className="text-lg flex items-center gap-2">
            <Brain className="w-5 h-5 text-purple-600" />
            AI Pre-Call Intelligence: {taskContext.taskTitle}
          </CardTitle>
          <div className="flex items-center gap-4 text-sm text-purple-700">
            <span>Patient: {taskContext.patientName}</span>
            <span>Priority: {taskContext.priority}</span>
            <span className="flex items-center gap-1">
              <Clock className="w-4 h-4" />
              {taskInsights.length} insights ready
            </span>
          </div>
        </CardHeader>
      </Card>

      {/* Task Context Summary */}
      <Card className="border-blue-200">
        <CardHeader className="bg-blue-50 pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-600" />
            Task Context Summary
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <span className="text-sm font-medium text-gray-600">Task Type:</span>
              <p className="text-sm">{taskContext.taskType}</p>
            </div>
            <div>
              <span className="text-sm font-medium text-gray-600">Priority:</span>
              <Badge className={getPriorityColor(taskContext.priority.toLowerCase())}>
                {taskContext.priority}
              </Badge>
            </div>
          </div>
          <div>
            <span className="text-sm font-medium text-gray-600">Description:</span>
            <p className="text-sm text-gray-800">{taskContext.description}</p>
          </div>
        </CardContent>
      </Card>

      {/* AI Insights */}
      <div className="space-y-4">
        {taskInsights.map((insight) => (
          <Card key={insight.id} className="border-l-2 border-l-gray-300">
            <CardContent className="p-4 space-y-3">
              <div className="flex items-start justify-between">
                <div className="flex items-center gap-2">
                  <div className={`p-2 rounded-lg ${getInsightColor(insight.type)}`}>
                    {getInsightIcon(insight.type)}
                  </div>
                  <div>
                    <h4 className="font-semibold text-gray-900">{insight.title}</h4>
                    <p className="text-sm text-gray-600">{insight.description}</p>
                  </div>
                </div>
                <div className="flex flex-col items-end gap-1">
                  <Badge className={getPriorityColor(insight.priority)}>
                    {insight.priority.toUpperCase()}
                  </Badge>
                  <div className="flex gap-2 text-xs text-gray-500">
                    <span>{Math.round(insight.confidence * 100)}% confidence</span>
                    <span>•</span>
                    <span>{Math.round(insight.taskRelevance * 100)}% relevant</span>
                  </div>
                </div>
              </div>

              <div className="bg-blue-50 p-3 rounded-lg">
                <h5 className="text-sm font-medium text-blue-900 mb-2 flex items-center gap-1">
                  <Lightbulb className="w-4 h-4" />
                  Suggested Questions
                </h5>
                <ul className="space-y-1">
                  {insight.suggestedQuestions.map((question, index) => (
                    <li key={index} className="text-sm text-blue-800 flex items-center gap-2">
                      <ChevronRight className="w-3 h-3" />
                      {question}
                    </li>
                  ))}
                </ul>
              </div>

              <div className="flex justify-between items-center text-xs text-gray-500">
                <span>Source: {insight.evidenceSource}</span>
                <span>Updated: {insight.lastUpdated}</span>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Call Action */}
      <Card className="border-green-200">
        <CardContent className="p-6">
          <div className="text-center space-y-4">
            <div>
              <h3 className="font-semibold text-gray-900 mb-2">Ready to Start AI-Enhanced Call</h3>
              <p className="text-sm text-gray-600">
                All insights have been prepared. The call interface will provide real-time assistance based on this intelligence.
              </p>
            </div>
            <Button 
              onClick={onStartCall} 
              className="w-full bg-[#1E4D36] hover:bg-[#2A6349] h-12 text-lg"
            >
              <Brain className="mr-2" size={20} />
              Start Task-Integrated Call
              <Badge className="ml-2 bg-green-500 text-white">
                {taskInsights.length} Insights Ready
              </Badge>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
