
import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { CheckCircle, AlertTriangle, TrendingUp, Calendar, Clock, Shield, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { ClinicalNote } from '@/types/billingBreakdown';
import { validateBillingReadiness, generateClinicalNotes } from '@/utils/billingValidation';

interface MonthlyStabilityReviewProps {
  task: any;
  onComplete: () => void;
  timer: number;
  formatTime: (seconds: number) => string;
}

export const MonthlyStabilityReview: React.FC<MonthlyStabilityReviewProps> = ({
  task,
  onComplete,
  timer,
  formatTime
}) => {
  const { toast } = useToast();
  const [stabilityMetrics, setStabilityMetrics] = useState({
    mood: '',
    medication: '',
    sleep: '',
    functionality: '',
    triggers: ''
  });
  const [careRecommendations, setCareRecommendations] = useState('');
  const [isCompleted, setIsCompleted] = useState(false);
  const [confirmSubmission, setConfirmSubmission] = useState(false);

  // Billing-related state
  const [clinicalNotes, setClinicalNotes] = useState<ClinicalNote>({
    stabilityAssessment: '',
    functionalStatus: '',
    riskFactors: '',
    interventions: '',
    followUpPlan: '',
    medicationReview: '',
    careCoordination: ''
  });

  const timeSpentMinutes = Math.floor(timer / 60);
  const validation = validateBillingReadiness(clinicalNotes, timeSpentMinutes);

  const handleMetricChange = (metric: string, value: string) => {
    setStabilityMetrics(prev => ({
      ...prev,
      [metric]: value
    }));
  };

  const handleAutoFillNotes = () => {
    const autoGeneratedNotes = generateClinicalNotes(stabilityMetrics);
    setClinicalNotes(prev => ({
      ...prev,
      ...autoGeneratedNotes
    }));
    
    toast({
      title: "Clinical Notes Auto-Generated",
      description: "Review and modify the generated notes as needed.",
    });
  };

  const handleNoteChange = (field: keyof ClinicalNote, value: string) => {
    setClinicalNotes(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleComplete = () => {
    // Validate that all required fields are filled
    const requiredFields = Object.values(stabilityMetrics).every(value => value.trim() !== '');
    
    if (!requiredFields || !careRecommendations.trim()) {
      toast({
        title: "Incomplete Review",
        description: "Please complete all stability metrics and care recommendations.",
        variant: "destructive"
      });
      return;
    }

    if (!validation.isValid) {
      toast({
        title: "Billing Documentation Incomplete",
        description: "Please complete all required clinical documentation before submitting.",
        variant: "destructive"
      });
      return;
    }

    if (!confirmSubmission) {
      toast({
        title: "Confirmation Required",
        description: "Please confirm that all documentation is accurate and complete.",
        variant: "destructive"
      });
      return;
    }

    setIsCompleted(true);
    
    toast({
      title: "Monthly Stability Review Completed",
      description: `Review completed in ${formatTime(timer)} and submitted for billing.`,
    });

    setTimeout(() => {
      onComplete();
    }, 1500);
  };

  const getMetricColor = (value: string) => {
    switch (value) {
      case 'improved': return 'bg-green-50 text-green-700 border-green-200';
      case 'stable': return 'bg-blue-50 text-blue-700 border-blue-200';
      case 'declined': return 'bg-red-50 text-red-700 border-red-200';
      default: return 'bg-gray-50 text-gray-700 border-gray-200';
    }
  };

  const getFieldStatus = (field: keyof ClinicalNote) => {
    const requirement = validation.requiredFields.find(req => req.field === field);
    return requirement?.completed || false;
  };

  if (isCompleted) {
    return (
      <Card className="border-green-200 bg-green-50">
        <CardContent className="p-6 text-center">
          <CheckCircle className="mx-auto text-green-600 mb-4" size={48} />
          <h3 className="text-lg font-semibold text-green-800 mb-2">
            Monthly Stability Review Completed
          </h3>
          <p className="text-green-700">
            Patient stability assessment has been documented and submitted for billing.
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header with Timer and Billing Status */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <Calendar className="text-blue-600" size={24} />
              <div>
                <CardTitle className="text-xl">Monthly Stability Review</CardTitle>
                <p className="text-sm text-gray-600 mt-1">
                  Comprehensive assessment of patient's mental health stability over the past month
                </p>
              </div>
            </div>
            <div className="flex items-center gap-4">
              <div className="flex items-center gap-2">
                <Clock className="w-4 h-4 text-gray-500" />
                <Badge className="bg-blue-50 text-blue-800 border-blue-200 font-mono">
                  {formatTime(timer)}
                </Badge>
              </div>
              <div className="flex items-center gap-2">
                <Shield className="w-4 h-4 text-blue-600" />
                <Badge className={validation.isValid ? "bg-green-100 text-green-800" : "bg-yellow-100 text-yellow-800"}>
                  Billing: {validation.completionPercentage}%
                </Badge>
              </div>
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Stability Metrics Assessment */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <TrendingUp className="text-green-600" size={20} />
            Stability Metrics Assessment
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {[
            { key: 'mood', label: 'Mood Stability', description: 'Overall mood patterns and emotional regulation' },
            { key: 'medication', label: 'Medication Adherence', description: 'Compliance with prescribed medications' },
            { key: 'sleep', label: 'Sleep Patterns', description: 'Quality and consistency of sleep' },
            { key: 'functionality', label: 'Daily Functioning', description: 'Ability to perform daily activities' },
            { key: 'triggers', label: 'Trigger Management', description: 'Response to identified triggers and stressors' }
          ].map(({ key, label, description }) => (
            <div key={key} className="space-y-2">
              <div>
                <label className="text-sm font-medium text-gray-700">{label}</label>
                <p className="text-xs text-gray-500">{description}</p>
              </div>
              <div className="flex gap-2">
                {['improved', 'stable', 'declined'].map((status) => (
                  <Button
                    key={status}
                    variant={stabilityMetrics[key as keyof typeof stabilityMetrics] === status ? "default" : "outline"}
                    size="sm"
                    onClick={() => handleMetricChange(key, status)}
                    className={
                      stabilityMetrics[key as keyof typeof stabilityMetrics] === status 
                        ? getMetricColor(status) 
                        : ''
                    }
                  >
                    {status.charAt(0).toUpperCase() + status.slice(1)}
                  </Button>
                ))}
              </div>
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Care Recommendations with Auto-fill */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <AlertTriangle className="text-amber-600" size={20} />
              Care Recommendations
            </CardTitle>
            <Button 
              onClick={handleAutoFillNotes}
              variant="outline"
              size="sm"
              className="border-blue-300 text-blue-700 hover:bg-blue-100"
              disabled={Object.values(stabilityMetrics).some(v => !v)}
            >
              Auto-Fill Clinical Notes
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            <label className="text-sm font-medium text-gray-700">
              Based on this month's assessment, what are your care recommendations?
            </label>
            <Textarea
              placeholder="Document recommended care plan adjustments, intervention strategies, follow-up requirements, and any concerns that need attention..."
              value={careRecommendations}
              onChange={(e) => setCareRecommendations(e.target.value)}
              className="min-h-24"
            />
          </div>
        </CardContent>
      </Card>

      {/* Billing Readiness Section */}
      <Card className="border-blue-200">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Shield className="text-blue-600" size={20} />
            Billing Readiness - Clinical Documentation
            <Badge className={validation.isValid ? "bg-green-100 text-green-800" : "bg-yellow-100 text-yellow-800"}>
              {validation.completionPercentage}% Complete
            </Badge>
          </CardTitle>
          <div className="flex items-center gap-4 text-sm text-gray-600">
            <div className="flex items-center gap-1">
              <Clock size={16} />
              <span>{timeSpentMinutes} minutes logged</span>
            </div>
            <div className="flex items-center gap-1">
              <FileText size={16} />
              <span>CPT Code: {task?.cptCode || '99484'}</span>
            </div>
          </div>
        </CardHeader>

        <CardContent className="space-y-6">
          {/* Progress Overview */}
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span>Documentation Progress</span>
              <span>{validation.completionPercentage}%</span>
            </div>
            <Progress value={validation.completionPercentage} className="h-2" />
          </div>

          {/* Clinical Notes Fields */}
          <div className="space-y-4">
            <h4 className="font-medium">Required Clinical Documentation</h4>
            
            {Object.entries(clinicalNotes).map(([field, value]) => {
              const fieldKey = field as keyof ClinicalNote;
              const isComplete = getFieldStatus(fieldKey);
              const requirement = validation.requiredFields.find(req => req.field === field);
              
              return (
                <div key={field} className="space-y-2">
                  <div className="flex items-center gap-2">
                    <label className="text-sm font-medium capitalize">
                      {field.replace(/([A-Z])/g, ' $1').trim()}
                    </label>
                    {isComplete ? (
                      <CheckCircle className="text-green-600" size={16} />
                    ) : (
                      <AlertTriangle className="text-yellow-600" size={16} />
                    )}
                  </div>
                  <Textarea
                    value={value}
                    onChange={(e) => handleNoteChange(fieldKey, e.target.value)}
                    placeholder={requirement?.description || `Enter ${field}...`}
                    className={isComplete ? "border-green-300" : "border-yellow-300"}
                    rows={2}
                  />
                  <div className="text-xs text-gray-500">
                    {value.length} characters • {requirement?.description}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Validation Summary */}
          {(validation.errors.length > 0 || validation.warnings.length > 0) && (
            <Card className="border-yellow-200 bg-yellow-50">
              <CardContent className="p-4">
                <h4 className="font-medium text-yellow-800 mb-2">Validation Summary</h4>
                {validation.errors.length > 0 && (
                  <div className="mb-2">
                    <p className="text-sm font-medium text-red-700">Errors:</p>
                    <ul className="text-sm text-red-600 list-disc list-inside">
                      {validation.errors.map((error, index) => (
                        <li key={index}>{error}</li>
                      ))}
                    </ul>
                  </div>
                )}
                {validation.warnings.length > 0 && (
                  <div>
                    <p className="text-sm font-medium text-yellow-700">Warnings:</p>
                    <ul className="text-sm text-yellow-600 list-disc list-inside">
                      {validation.warnings.map((warning, index) => (
                        <li key={index}>{warning}</li>
                      ))}
                    </ul>
                  </div>
                )}
              </CardContent>
            </Card>
          )}
        </CardContent>
      </Card>

      {/* Summary and Actions */}
      <Card>
        <CardContent className="p-6">
          <div className="space-y-4">
            {/* Progress Summary */}
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-600">Assessment Progress:</span>
                <Badge variant="outline">
                  {Object.values(stabilityMetrics).filter(v => v).length}/5 metrics assessed
                </Badge>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-sm text-gray-600">Billing Ready:</span>
                <Badge className={validation.isValid ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800"}>
                  {validation.isValid ? 'Yes' : 'No'}
                </Badge>
              </div>
            </div>

            {/* Confirmation Checkbox */}
            <div className="flex items-center space-x-2">
              <Checkbox 
                id="confirm-submission"
                checked={confirmSubmission}
                onCheckedChange={(checked) => setConfirmSubmission(checked as boolean)}
              />
              <label 
                htmlFor="confirm-submission" 
                className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
              >
                I confirm that all clinical documentation is accurate and complete for billing submission
              </label>
            </div>

            {/* Submit Button */}
            <Button 
              onClick={handleComplete}
              className="w-full bg-[#1E4D36] hover:bg-[#2A6349]"
              disabled={
                Object.values(stabilityMetrics).some(v => !v) || 
                !careRecommendations.trim() || 
                !validation.isValid || 
                !confirmSubmission
              }
            >
              Complete Review & Submit for Billing
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
