
import React, { useState } from 'react';
import { useToast } from '@/hooks/use-toast';
import { ClinicalNote } from '@/types/billingBreakdown';
import { generateClinicalNotes } from '@/utils/billingValidation';
import { StabilityReviewHeader } from './monthly-stability/StabilityReviewHeader';
import { StabilityAssessmentStep } from './monthly-stability/StabilityAssessmentStep';
import { DocumentationStep } from './monthly-stability/DocumentationStep';
import { FinalReviewStep } from './monthly-stability/FinalReviewStep';
import { StabilityCompletionCard } from './monthly-stability/StabilityCompletionCard';
import type { CareTaskViewModel } from './types';

interface MonthlyStabilityReviewProps {
  task: CareTaskViewModel;
  onComplete: () => void;
  timer: number;
  formatTime: (seconds: number) => string;
}

interface ChecklistItem {
  id: string;
  label: string;
  description: string;
  completed: boolean;
  value?: string;
}

export const MonthlyStabilityReview: React.FC<MonthlyStabilityReviewProps> = ({
  task,
  onComplete,
  timer,
  formatTime
}) => {
  const { toast } = useToast();
  
  // Stability metrics checklist
  const [stabilityChecklist, setStabilityChecklist] = useState<ChecklistItem[]>([
    {
      id: 'mood',
      label: 'Mood Stability Assessment',
      description: 'How has the patient\'s mood been over the past month?',
      completed: false,
      value: ''
    },
    {
      id: 'medication',
      label: 'Medication Adherence Review',
      description: 'Is the patient taking medications as prescribed?',
      completed: false,
      value: ''
    },
    {
      id: 'sleep',
      label: 'Sleep Pattern Evaluation',
      description: 'How are the patient\'s sleep patterns?',
      completed: false,
      value: ''
    },
    {
      id: 'functionality',
      label: 'Daily Functioning Check',
      description: 'How well is the patient managing daily activities?',
      completed: false,
      value: ''
    },
    {
      id: 'triggers',
      label: 'Trigger Management Review',
      description: 'How is the patient handling stress and triggers?',
      completed: false,
      value: ''
    }
  ]);

  // Clinical documentation with smart defaults
  const [clinicalNotes, setClinicalNotes] = useState<ClinicalNote>({
    stabilityAssessment: '',
    functionalStatus: '',
    riskFactors: '',
    interventions: '',
    followUpPlan: '',
    medicationReview: '',
    careCoordination: ''
  });

  const [currentStep, setCurrentStep] = useState<'assessment' | 'documentation' | 'review'>('assessment');
  const [isCompleted, setIsCompleted] = useState(false);
  const [finalConfirmation, setFinalConfirmation] = useState(false);

  const completedAssessments = stabilityChecklist.filter(item => item.completed).length;
  const totalAssessments = stabilityChecklist.length;

  const handleStabilityItemChange = (id: string, value: string) => {
    setStabilityChecklist(prev => prev.map(item => 
      item.id === id 
        ? { ...item, value, completed: value !== '' }
        : item
    ));
  };

  const handleAutoFillDocumentation = () => {
    const stabilityMetrics = stabilityChecklist.reduce((acc, item) => {
      acc[item.id] = item.value;
      return acc;
    }, {} as Record<string, string>);

    const autoGeneratedNotes = generateClinicalNotes(stabilityMetrics);
    setClinicalNotes(prev => ({
      ...prev,
      ...autoGeneratedNotes
    }));
    
    toast({
      title: "Documentation Auto-Generated",
      description: "Smart defaults have been filled in. Please review and customize as needed.",
    });
  };

  const handleNoteChange = (field: keyof ClinicalNote, value: string) => {
    setClinicalNotes(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const handleNextStep = () => {
    if (currentStep === 'assessment') {
      if (completedAssessments === totalAssessments) {
        handleAutoFillDocumentation();
        setCurrentStep('documentation');
      } else {
        toast({
          title: "Assessment Incomplete",
          description: `Please complete ${totalAssessments - completedAssessments} more assessment(s) before proceeding.`,
          variant: "destructive"
        });
      }
    } else if (currentStep === 'documentation') {
      setCurrentStep('review');
    }
  };

  const handleBackStep = () => {
    if (currentStep === 'documentation') {
      setCurrentStep('assessment');
    } else if (currentStep === 'review') {
      setCurrentStep('documentation');
    }
  };

  const handleComplete = () => {
    if (!finalConfirmation) {
      toast({
        title: "Confirmation Required",
        description: "Please confirm that all information is accurate before submitting.",
        variant: "destructive"
      });
      return;
    }

    setIsCompleted(true);
    
    toast({
      title: "Review Completed Successfully",
      description: `Monthly stability review completed in ${formatTime(timer)}.`,
    });

    setTimeout(() => {
      onComplete();
    }, 1500);
  };

  if (isCompleted) {
    return <StabilityCompletionCard />;
  }

  return (
    <div className="space-y-6">
      <StabilityReviewHeader
        timer={timer}
        formatTime={formatTime}
        currentStep={currentStep}
        completedAssessments={completedAssessments}
        totalAssessments={totalAssessments}
      />

      {currentStep === 'assessment' && (
        <StabilityAssessmentStep
          stabilityChecklist={stabilityChecklist}
          onItemChange={handleStabilityItemChange}
          onNext={handleNextStep}
          completedAssessments={completedAssessments}
          totalAssessments={totalAssessments}
        />
      )}

      {currentStep === 'documentation' && (
        <DocumentationStep
          clinicalNotes={clinicalNotes}
          onNoteChange={handleNoteChange}
          onNext={handleNextStep}
          onBack={handleBackStep}
        />
      )}

      {currentStep === 'review' && (
        <FinalReviewStep
          stabilityChecklist={stabilityChecklist}
          timer={timer}
          finalConfirmation={finalConfirmation}
          onConfirmationChange={setFinalConfirmation}
          onComplete={handleComplete}
          onBack={handleBackStep}
        />
      )}
    </div>
  );
};
